# this is an example config file

http_listen_port = 3000

db_host = "192.168.0.80"
db_user = "root"
db_pass = "asdf"
db_name = "sensordata"

log_to_output = true

# adc scaling:
sensorscale = 1.1123
